theme: jekyll-theme-minimal
title: TheWestBobersWebsite
description: Pivotal Movies
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: data
    url: "/data"
redirects:
  "/": "/README"