theme: jekyll-theme-minimal
title: TheWestBobersWebsite
description: Pivotal Movies
show_downloads: False
navigation:
  - title: Introduction
    url: "/introduction"
  - title: Our Method
    url: "/our_method"
  - title: The Results
    url: "/the_results"
  - title: Method Evaluation
    url: "/method_evaluation"
  - title: Conclusion
    url: "/conclusion"
  - title: Ethics
    url: "/ethics"
  - title: The Data
    url: "/the_data"
redirects:
  "/": "/README"
