theme: jekyll-theme-minimal
title: TheWestBobersWebsite
description: Pivotal Movies
show_downloads: False
navigation:
  - title: Home
    url: /
      - title: Home
    url: "/README"
redirects:
  "/": "/README"
  redirects:
  "/index": "/README"
